### ISSUE TITLE
Entities Map and subscriptions buttons stay  unclickable

### ISSUE THREAD

**Issue by pgibert** [VM9/fiware-orion-explorer#3]
Hello
nice job .
 It works  for me regarding 'Entities Grid' 's button ( pointing to my own Orion broker)  but 
 both Entities Map and subscriptions buttons stay  unclickable . 

May i miss  something or the features are not yet available  ?
best regards

**Comment by LeonanCarvalho** [comment]
Hi!

Thanks, we appreciate  !

The backend feature is read for query [geo entities](https://github.com/VM9/orion-explorer-php-frame-work/blob/develop/example/06_figuardian_quering.php#L103) and (get all subscriptions)[https://github.com/VM9/orion-explorer-php-frame-work/blob/develop/src/Orion/Context/SubscriptionEntity.php#L44] but front-end end isn't ready, we are looking for a free map plugin ([leaflet](https://github.com/angular-ui/ui-leaflet) is under evaluation).

So these features isn't available yet.

Greetings.

**Comment by LeonanCarvalho** [comment]
@pgibert I just commited a preview of this development to master branch, its possible to view entities with geo attributes(only geo:json and geometries type "POINT" was tested)  and  list subscriptions.

The next steps will be to build a kind of "CRUD" to this viewers.

**Comment by pgibert** [comment]
Thanks Leon . it works nicely  for the list of subscriptions . it really gives added value to Orion to have this possibility of displaying.
